In [46]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline

##Uploading Dataframe

In [47]:
df = pd.read_csv('/content/audible_uncleaned.csv')
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB

##Data cleaning

###Finding duplicates

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df['author'].nunique()

48374

###Clean `author` and `narrator` columns

In [51]:
df['author'] = df['author'].str.replace('Writtenby:', '', regex=False)
df['narrator'] = df['narrator'].str.replace('Narratedby:', '', regex=False)
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
48192,Dracula [Audible Edition],BramStoker,"AlanCumming,TimCurry,SimonVance,",15 hrs and 28 mins,20-02-12,English,4.5 out of 5 stars54 ratings,"1,003.00"
18101,Måste man älska sin mamma?,IrénePettersson,KristinaLeon,2 hrs and 25 mins,22-05-19,swedish,Not rated yet,233.00
3456,Chelsey,ChelseyShannon,AsmeretGhebremichael,3 hrs and 39 mins,04-11-09,English,Not rated yet,568.00
71243,Appleby Farm,CathyBramley,ColleenPrendergast,13 hrs and 18 mins,15-10-15,English,Not rated yet,820.00
35273,The Death Gap,DavidA.Ansell,PeterBerkrot,7 hrs and 21 mins,23-05-17,English,Not rated yet,891.00
32437,The Wellness Revelation,AlisaKeeton,SarahZimmerman,7 hrs and 51 mins,03-10-17,English,Not rated yet,762.00
19605,Finding My Virginity (German edition),RichardBranson,MichaelJ.Diekmann,21 hrs and 17 mins,12-01-22,german,Not rated yet,"1,038.00"
81711,Amazing Diving Stories,JohnBantin,DeanWilliamson,8 hrs and 50 mins,16-05-13,English,Not rated yet,569.00
61699,Reconcilable Differences,CateCochran,CateCochran,6 hrs and 34 mins,30-05-21,English,Not rated yet,609.00
44014,The Other Man,FarhadJ.Dadyburjor,AriyanKassam,8 hrs and 29 mins,02-11-21,English,Not rated yet,844.00

Clean `price` and `language` column

In [52]:
df['price'] = df['price'].str.replace(r'\..*', '', regex=True)
df['language'] = df['language'].str.capitalize()
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
30266,Business Start-Up Success Made Simple,BrianTracy,BrianTracy,11 hrs and 17 mins,19-10-11,English,Not rated yet,"1,172"
21017,Queen Victoria's Mysterious Daughter,LucindaHawksley,JenniferM.Dixon,16 hrs and 2 mins,12-06-18,English,Not rated yet,"1,003"
81036,The Majors,JohnFeinstein,JohnFeinstein,2 hrs and 39 mins,04-06-13,English,Not rated yet,500
49285,A House of Pomegranates,OscarWilde,"NoelBadrian,CraigFranklin,ChrisMarcellus,",3 hrs and 41 mins,02-12-20,English,Not rated yet,383
34307,"Beginners Yoga, Volume 1",SueFuller,SueFuller,1 hr and 2 mins,12-08-08,English,Not rated yet,531
77706,Sugar Skulls,"LisaMantchev,GlennDallas","ScottMerriman,KateRudd",11 hrs and 7 mins,10-11-15,English,Not rated yet,352
82124,Aussie Bites,MargaretClark,StigWemyss,44 mins,10-08-06,English,Not rated yet,166
65237,Compassionate Conversations,"DianeMushoHamilton,GabrielMenegaleWilson,Kimbe...",KaliswaBrewster,7 hrs and 54 mins,27-01-21,English,Not rated yet,703
64793,Wut und Böse,Ciani-SophiaHoeder,Ciani-SophiaHoeder,4 hrs and 53 mins,27-09-21,German,Not rated yet,434
69138,"Feng Shui - Transformez votre espace, changez ...",KarenRauchCarter,CarolineBoyer,2 hrs and 20 mins,14-01-08,French,Not rated yet,600

###Clean `author` and 'narrator`

In [53]:
df['author'] = df['author'].str.replace(r'(?<=[a-z,])(?=[A-Z])', ' ', regex = True)
df['narrator'] = df['narrator'].str.replace(r'(?<=[a-z,])(?=[A-Z])', ' ', regex = True)
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
12361,"Puolalainen ""kommandojoukko""",N.N.,Leo Niemi,33 mins,15-01-20,Finnish,Not rated yet,233
71601,Bossy Grump,Nicole Snow,"Rock Engle, Carly Robins",14 hrs and 48 mins,29-06-21,English,3 out of 5 stars1 rating,836
20215,"Robin Williams, American Master",Stephen Spignesi,Roger Wayne,7 hrs and 34 mins,24-11-20,English,Not rated yet,703
28233,Business anders,"Stephan Heinrich, Andreas Buhr","Stephan Heinrich, Andreas Buhr",1 hr and 8 mins,14-12-21,German,Not rated yet,233
77160,Restore Me,J.L.Mac,"Christian Fox, Veronica Meunch",4 hrs and 10 mins,21-10-13,English,Not rated yet,820
55662,Zadig,Voltaire,Guillaume Ravoire,3 hrs and 12 mins,21-07-16,French,Not rated yet,641
17665,Detroit Rock City,Steve Miller,Steve Miller,10 hrs and 6 mins,09-07-13,English,Not rated yet,735
17272,Ringo,Michael Seth Starr,Peter Berkrot,15 hrs and 59 mins,09-02-16,English,Not rated yet,"1,172"
73714,Wish Upon a Duke,JRSalisbury,Mary Sarah,6 hrs and 59 mins,26-10-21,English,Not rated yet,586
48598,The Princesse de Clèves,"Nancy Mitford, Madamede Lafayette, Selina Hast...",Polly Edsell,6 hrs and 3 mins,23-08-18,English,Not rated yet,835

###Change the type of `relesedate`

In [54]:
df['releasedate'] = pd.to_datetime(df['releasedate'], errors = 'coerce')
df.head()

/tmp/ipykernel_2146/1468591807.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['releasedate'] = pd.to_datetime(df['releasedate'], errors = 'coerce')

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2 hrs and 20 mins,2008-04-08,English,5 out of 5 stars34 ratings,468
1,The Burning Maze,Rick Riordan,Robbie Daymond,13 hrs and 8 mins,2018-01-05,English,4.5 out of 5 stars41 ratings,820
2,The Deep End,Jeff Kinney,Dan Russell,2 hrs and 3 mins,2020-06-11,English,4.5 out of 5 stars38 ratings,410
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,11 hrs and 16 mins,2021-05-10,English,4.5 out of 5 stars12 ratings,615
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,10 hrs,2010-01-13,English,4.5 out of 5 stars181 ratings,820

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  datetime64[ns]
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: datetime64[ns](1), object(7)
memory usage: 5.3+ MB

###Working with `time` column

In [56]:
df['time'] = df['time'].str.replace(r'[a-zA-Z]', '', regex = True)
df['time'] = df['time'].str.strip().str.split()
df.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,"[2, 20]",2008-04-08,English,5 out of 5 stars34 ratings,468
1,The Burning Maze,Rick Riordan,Robbie Daymond,"[13, 8]",2018-01-05,English,4.5 out of 5 stars41 ratings,820
2,The Deep End,Jeff Kinney,Dan Russell,"[2, 3]",2020-06-11,English,4.5 out of 5 stars38 ratings,410
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,"[11, 16]",2021-05-10,English,4.5 out of 5 stars12 ratings,615
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,[10],2010-01-13,English,4.5 out of 5 stars181 ratings,820

In [57]:
def convert_time(x):
    if len(x) >= 2:
      return int(x[0])*60 + int(x[1])
    elif len(x) < 2:
      return int(x[0])
    return None

df['time'] = df['time'].apply(convert_time)
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
39233,Conquerors,Roger Crowley,John Sackville,673,2015-09-17,English,5 out of 5 stars5 ratings,721
76497,The Checklist,Addie Woolridge,Adenrele Ojo,719,2021-01-06,English,Not rated yet,"1,008"
27913,情報の選球眼 真実の収集・分析・発信,山本康正,濱岡敬祐,375,2022-10-02,Japanese,Not rated yet,837
51064,The Willow Marsh Murder,Karen Charlton,Michael Page,642,2021-12-31,English,Not rated yet,703
55578,Moon Lake,Joe R.Lansdale,Jason Culp,557,2021-06-23,English,Not rated yet,500
4515,Ganesha ke Sahasik Kaarname [The Adventures of...,Mrs Rashmi Sundaram,"Mr Sumit Kaul, Master Sidh Sundaram, Mrs Rashm...",38,2021-05-04,Hindi,Not rated yet,139
28925,Sales Management for Dummies,Butch Bellah,Chris Sorensen,813,2019-09-24,English,Not rated yet,703
59262,"Behold, Here's Poison",Georgette Heyer,Matt Addis,530,2021-09-30,English,Not rated yet,888
78728,Wicked Cowboy Charm,Carolyn Brown,Chelsea Hatfield,507,2017-01-31,English,Not rated yet,500
84142,Naked Eye,Francine Pascal,Elizabeth Evans,7,2014-03-23,English,Not rated yet,668

###Cleaning foreign names

In [58]:
mask = ~df['name'].str.contains(r'^[A-Za-z0-9]', regex = True, na = False)
df = df.drop(index = df[mask].index)
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
37939,12 Years a Slave,Solomon Northup,Mirron Willis,490,2021-02-24,English,Not rated yet,234
34524,Dieta Sirt,Sara Marino,Sabrina Maggiani,145,2021-04-29,Italian,Not rated yet,459
21034,Arthur Conan Doyle,Hesketh Pearson,Tim Pigott-Smith,157,2002-12-29,English,Not rated yet,422
32458,What Does It Feel Like to Die?,Jennie Dear,Andrea Gallo,492,2019-06-25,English,Not rated yet,820
41261,If History Has Taught Us Anything,Farhat Nasreen,Shernaz Patel,375,2019-06-11,English,4.5 out of 5 stars2 ratings,331
25593,Steadfast,Lizzie Armitstead,"Lizzie Armitstead, Katy Sobey",438,2017-04-20,English,Not rated yet,"1,063"
61001,Devilish Obsession,Eliana Salome,"Pepper Laramie, Lance Greenfield",351,2021-12-15,English,Not rated yet,703
38715,Sita: A Tale of Ancient Love,Bhanumathi Narasimhan,Anahita Uberoi,574,2022-03-16,English,Not rated yet,879
27490,"The AMA Handbook of Project Management, Fifth ...","Paul C.Dinsmore PMP-editor, Jeannette Cabanis-...",David Stifel,1546,2019-05-03,English,5 out of 5 stars4 ratings,820
4334,Addition and Subtraction,"Kim Mitzo Thompson, Karen Mitzo Hilderbrand, T...",Twin Sisters,110,2012-01-01,English,Not rated yet,140

###Working with `stars` column

In [59]:
df['stars'] = df['stars'].str.replace(r'[A-Za-z]', '', regex = True).str.strip().str.split()
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
39503,Andare per i luoghi del '68,Toni Capuozzo,Francesco Mei,189,2021-07-20,Italian,[],190
55736,Cashing In,Daniel Schinhofen,Andrea Parsneau,731,2021-12-17,English,[],836
78242,Cowboys in January,Jenny Klaire,"Robin Lewis, Natasha Lawless, Brett Galliford",313,2021-06-05,English,[],468
71151,Weather the Storm,Lisa Mondello,Paul Boehmer,165,2016-05-31,English,[],233
29180,Resumen de The First Mile de Scott D. Anthony,PMPManagement Factory,PMPManagement Factory,11,2021-02-06,Spanish,[],307
68347,A Call from Heaven,Josie Varga,Hillary Huber,361,2017-12-04,English,[],656
38660,2012,"Philip Coppens, Geoff Stray","Philip Coppens, Geoff Stray",107,2009-06-26,English,[],333
78805,Trusting Grace,Maggie Brendan,Rebecca Gallagher,599,2017-02-05,English,[],469
74122,The Bridled Tongue,Catherine Meyrick,Danielle Cohen,756,2021-04-05,English,"[4, 5, 1]",703
33213,500 quotes of Lao Tsu for meditation,Tzu Lao,Katie Haigh,96,2016-02-25,English,[],414

In [60]:
def convert_star(x):
  if len(x) >=2:
    return float(x[0])
  elif len(x) < 2:
    return None
  return None

df['stars'] = df['stars'].apply(convert_star)
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
59248,Walk the Wire,David Baldacci,"Kyf Brewer, Orlagh Cassidy",715,2020-04-16,English,4.0,323
85805,Schatten über Fort Fiory,Rhiannon Williams,Funda Vanroy,538,2021-08-04,German,NaN,501
57581,Aprender economia [Learn Economics],Paul Singer,João Domingues,459,2021-10-03,Portuguese,NaN,668
45954,Creatures of Passage,Morowa Yejidé,Morowa Yejidé,604,2021-03-16,English,NaN,"1,008"
64455,Nationalism,Rabindranath Tagore,Swetanshu Bora,3,2021-01-03,English,4.5,Free
48474,Plato's Republic,Plato,Ray Childs,706,2016-01-04,English,5.0,836
82227,Traitor,Amanda Mc Crina,Raphael Corkhill,522,2020-08-25,English,NaN,134
84770,Play,Javier Ruescas,"Javier Ruescas, Raúl García",695,2021-07-26,Spanish,NaN,767
57430,Lehman Brothers,i Minds,Luca James Lee,8,2009-09-15,English,NaN,65
42044,You've Got My Number,Angela Barton,Charlotte Strevens,500,2020-02-28,English,NaN,785

In [61]:
df['stars'] = df['stars'].fillna(df['stars'].mean().round(2))

In [62]:
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
61321,Secrets of the Baby Whisperer for Toddlers,"Tracy Hogg, Melinda Blau",Tracy Hogg,323,2019-11-01,English,5.00,651
61215,Play Dead,Harlen Coben,Melissa Bayern,1076,2021-09-30,English,4.46,873
30124,The Entrepreneur's Journey,Alon Braun,Peter Brook,260,2021-07-21,English,4.46,568
77535,The Lasaran,Dianne Duvall,Kirsten Potter,683,2020-04-21,English,4.46,703
2316,Evie und die Macht der Tiere,Matt Haig,Rufus Beck,257,2021-07-23,German,4.46,334
45780,Of One Blood; or The Hidden Self (AmazonClassi...,Pauline E.Hopkins,Noel Arthur,393,2021-06-07,English,4.46,844
86781,Il mio viaggio a New York,Piero Armenti,Alessio Mizzan,487,2021-03-03,Italian,4.46,574
56678,What Women Want When They Test Men,Bruce Bryans,Greg Zarcone,226,2017-11-09,English,4.50,501
18630,Lettere 1945-1950,Cesare Pavese,Giuliano Bonetto,616,2022-03-25,Italian,4.46,190
72807,Captured Heart,Heather Mc Collum,Timothy Campbell,599,2021-09-03,English,4.46,703

Convert dataframe to csv

In [63]:
df.to_csv('cleaned_data1.csv', index = False)